Mention wasm-features in `Readme.md`
argmin-rs/argmin pull request #167
Opened 2021-12-30 13:21 UTC by Glitchy-Tozier

When important features aren't mentioned, this can lead to [some confusion](https://github.com/dariogoetz/keyboard_layout_optimizer/pull/7#issuecomment-1001672035)

Therefore, I suggest quickly mentioning them. :)
This pull-request adds a mention about WebAssembly and the required features.

---

Eventually, it would be handy to have every existing feature described in the `Readme.md`. Nothing extensive, just a short mention that the feature exists and an overview of what it does.

2021-12-31 07:46 UTC, stefan-k requested changes
Thank you for this PR and apologies for the confusion this has caused! 

The reason why this wasn't documented so far is that this feature isn't well tested and not part of the CI (see #89) since I don't need this feature myself and haven't had time yet to get into it in detail. I have suggested minor changes to your PR to reflect that. 

If you have experience with compiling to WASM, I would be very very happy if you could add a check to the CI as well :)

2021-12-31 07:46 UTC, stefan-k commented on README.md
> +#### Required for WebAssembly
```suggestion
#### Experimental support for compiling to WebAssembly
```

2021-12-31 07:46 UTC, stefan-k commented on README.md
> +To prevent panics when compiling to WASM, one of the following features needs to be used:
```suggestion
When compiling to WASM, one of the following features must be used:
```

2021-12-31 07:46 UTC, stefan-k commented on README.md
> +
```suggestion
Note that WASM support is still experimental. Please report any issues you encounter when compiling argmin to WASM.

```

2022-01-01 15:55 UTC, Glitchy-Tozier commented
I've implemented the requested changes! :)

> If you have experience with compiling to WASM, I would be very very happy if you could add a check to the CI as well :)

I don't have much experience, unfortunately. _Maybe_ @dariogoetz could share his sources with you though. He has set up the infrastructure of our keyboard-project.

2022-01-02 08:31 UTC, stefan-k commented
Thanks for making the changes! I added the same text to `src/lib.rs` as I typically create the readme from there using `cargo readme`.

2022-01-02 08:37 UTC, stefan-k approved these changes

2022-01-02 08:44 UTC, merged

2022-01-02 10:36 UTC, Glitchy-Tozier commented
By the way, I'm just curious: When do you plan on releasing `v0.5.0`?

2022-01-02 19:13 UTC, stefan-k commented
I plan to release it until the end of January, hopefully sooner. But unfortunately I can't guarantee it ;)

2022-01-02 20:26 UTC, Glitchy-Tozier commented
Understood  :)

2022-01-10 07:48 UTC, stefan-k commented
v0.5.0 is released!

2022-01-10 07:58 UTC, Glitchy-Tozier commented
Amazing, thank you for notifying me! :)