Add a simple example of Nelder-Mead usage.
argmin-rs/argmin pull request #359
Opened 2023-05-27 06:46 UTC by cjordan

Hi,

Thanks for the effort that's been put into `argmin`. I've recently used the Nelder-Mead part successfully and it will be a great addition to my tool belt.

I felt the need to contribute a simple example, because over the last couple of years, I've tried a couple of times to use `argmin`, and the existing docs and examples were not clear enough for me.  I wanted to use Nelder-Mead, but I (even still) didn't know what a Rosenbrock function is in the existing example (Wikipedia suggests that this is a sensible thing to test optimisation algs, but my lack of familiarity was intimidating).  This PR contains another Nelder-Mead example, which demonstrates searching for a cubic polynomial's roots.  It also shows how to extract the optimised parameter from the `Executor` result, which was not obvious to me from the existing docs or examples.

Please feel free to edit what I've provided, and I'm open to suggestions on making this better.  My objective is to make what already is a well-polished library even more accessible, and allow people like myself to continue developing in Rust instead of having to write more code to access e.g. scipy optimize instead.

2023-06-12 20:17 UTC, stefan-k commented
Hi @cjordan, thanks a lot for this PR!! Improvements of documentation and examples are very welcome, and I'm very thankful for the effort you put into this! :) Having good documentation to make argmin more accessible is very important to me, but it is also a very time-cosuming task and as such every help is highly appreciated! 

I apologize for the very very late reply, unfortunately I've been rather busy over the past months and currently only have limited access to the internet (#360). 

Right now I have time for a rough review and I hope I'll be able to give a more in-depth review at a later stage (if even necessary).

2023-06-12 20:27 UTC, stefan-k requested changes
Thanks again for this very useful addition! I only have a couple of minor comments.

2023-06-12 20:27 UTC, stefan-k commented on argmin/Cargo.toml
> +name = "neldermead-simple"
I think I would prefer `neldermead-cubic`.

2023-06-12 20:27 UTC, stefan-k commented on argmin/examples/neldermead-simple.rs
> +        // Print our result in a custom way.
I think these two lines can be removed (people who have not looked at the other examples may be confused).

2023-06-12 20:27 UTC, stefan-k commented on argmin/src/solver/neldermead/mod.rs
> +//!
In theory, I am all in favor of advertising the example here. The problem however is, that this points to the current main branch. If people use older versions of argmin (and the corresponding docs) they may be led to an example which doesn't work for them. We have had this in the past, and decided to remove all links to examples in the docs. One could link to the corresponding example via the git tags; however, it is a major chore to update all links for every new version.

2023-06-13 02:36 UTC, cjordan commented
Hi @stefan-k, thanks for reviewing my PR, and I'm glad you find it useful. No worries about being late to reply; I understand the feeling of being busy!

 I agree with all of your points, and I've now made a new commit. Feel free to squash the commits (as I like to do to appease my OCD), or let me know if you want me to do it.

2023-06-21 17:10 UTC, stefan-k approved these changes
Thanks for you work and your patience! :) This looks good to me! :)

2023-06-21 17:21 UTC, merged