allow user to set ParticleSwarm's random number generator
argmin-rs/argmin pull request #383
Opened 2024-01-06 19:15 UTC by jonboh

Initially I had restricted the trait requirements for G (Generator) to be `Rng+SeedableRng`, however with just `Rng` a user is perfectly able to use a `SeedableRng`. 
In the tests I've done that. 
With this change we can fix the behaviour of ParticleSwarm in tests and bechmarks.

2024-01-06 20:03 UTC, stefan-k requested changes
Thanks a lot! Looks pretty good to me, I only have a few minor comments.

2024-01-06 20:03 UTC, stefan-k commented on argmin/src/solver/particleswarm/mod.rs
> +pub struct ParticleSwarm<P, F, G> {
Throughout argmin, `G` indicates a gradient, therefore using `G` for a generator may be confusing. I'm not sure though what a good alternative may be. Maybe `R` or even `Rng`?

2024-01-06 20:16 UTC, jonboh commented on argmin/src/solver/particleswarm/mod.rs
> +            rng_generator: rand::rngs::StdRng::seed_from_u64(42),
yeah it makes sense to keep the default non-deterministic instead of fixing the seed

2024-01-07 10:00 UTC, stefan-k requested changes
Thanks again! I only have one tiny comment, then it is good to go! :)

2024-01-07 10:01 UTC, jonboh commented on argmin/src/solver/particleswarm/mod.rs
> +    /// Defaults to `rand::rngs::StdRng::seed_from_u64(42)`
missed that! thanks

2024-01-07 10:57 UTC, stefan-k approved these changes
Thanks!

2024-01-07 10:57 UTC, merged