Added a few test cases for minmax.rs
argmin-rs/argmin pull request #389
Opened 2024-01-16 20:44 UTC by Shreyan11

As the title says,I've added a few test cases.Please do check if it's all right,or if I need to make any improvements in the test cases,so that I can write unit tests for the rest of the types as well.
I'm open to all suggestions,thank you in advance.

2024-01-16 21:08 UTC, stefan-k requested changes
Thanks for this PR! The tests look good, but I have a few comments regarding other changes.

2024-01-16 21:08 UTC, stefan-k commented on README.md
> +=======
Please remove these lines

2024-01-16 21:08 UTC, stefan-k commented on README.md
> +>>>>>>> main
Please remove this line

2024-01-16 21:08 UTC, stefan-k commented on README.md
There should be no changes in this file compared to the main branch.

2024-01-16 21:08 UTC, stefan-k commented on argmin-math/src/primitives/l1norm.rs
> +
Please remove empty line

2024-01-16 21:08 UTC, stefan-k commented on argmin-math/src/primitives/minmax.rs
> +
Please remove empty line

2024-01-17 05:04 UTC, Shreyan11 reviewed
I've made the changed and will make another PR ,please let me know what you think about it.
I'm open to all suggestions

2024-01-17 05:11 UTC, closed without merging